import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FREE HADA 프리랜서를 위한 플랫폼",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(
        inter.className, 
        "min-h-screen w-full flex justify-center", 
        { "debug-screens": process.env.NODE_ENV === "development"})}
      >
        {children}
      </body>
    </html>
  );
}
